#+AUTHOR: lambdart
#+EMAIL: lambdart@protonmail.com
#+DESCRIPTION: Elisp interface to query and show documenation using dash!
#+KEYWORDS: emacs, dash, dash docs, documentation
#+LANGUAGE: en

* Introduction

  This package provides an =Elisp= interface to query
  and show documentation using [[http://www.kapeli.com/dash][Dash]] docsets.

  It doesn't require =Dash= app, we rely on any
  =html= file browser, however =eww= is recommended!

* Version

  - Alpha 0.0.3

* Requirements

  - SQLite3

* Dependencies

  - xml
  - url
  - url-http
  - mm-decode
  - json
  - cl-macs

* Tested on

  | Emacs   | 27.1 | 28.0 |   |   |
  | FreeBSD | 12.1 |      |   |   |
  | OpenBSD |  6.8 |      |   |   |

* Installation
** Manually

   Clone =ddoc-el= repository to an arbitrary location:

   #+BEGIN_SRC sh

   $ git clone https://github.com/lambdart/ddoc-el ~/.emacs.d/site-elisp/ddoc

   #+END_SRC

   Add =Dash-docs= directory to =load-path= in your
   Emacs initialization file (~init.el~) and load it.

   #+BEGIN_SRC emacs-lisp

   ;; add to load-path
   (add-to-list 'load-path "/replace/me/to/ddoc/full/path")

   ;; load ddoc feature
   (require 'ddoc nil t)

   #+END_SRC

   - Note: For a more dynamic approach:
     - =M-x load-file RET=
     - =M-x load-library RET ddoc RET=

** Compile

   * Note: Optional (recommended).

   To compile the files to the =Elisp= byte-compiled representation:

   #+BEGIN_SRC sh

   [at-ddoc-root-directory]$ make

   #+END_SRC

** Docsets

   Dash-docs uses the same docsets as [[http://www.kapeli.com/dash][Dash]].

   You can install them with =M-x ddoc-install-docset= for the
   official docsets or =M-x ddoc-install-user-docset= for user
   contributed docsets (experimental).

   To install a docset from a file in your drive you can use
   =M-x ddoc-install-docset-from-file=.

   That function takes as input a ~tgz~ file that you obtained,
   starting from a folder named =<docset-name>.docset=, with the command:

   #+BEGIN_SRC sh

   tar --exclude='.DS_Store' -cvzf <docset-name>.tgz <docset-name>.docset

   #+END_SRC

   as explained [[https://kapeli.com/docsets#dashdocsetfeed][here]].

* Customize

  - =ddoc-docsets-path= :: is the prefix for your docsets,
    defaults to =~/.docsets=.

  - =ddoc-min-length= :: tells ddoc from which length to start
    searching, defaults to =3=.

  - =ddoc-browser-func= :: is a function to encapsulate the way to browse
    Dash' docsets, defaults to =browse-url=. For example, if you want to use eww to
    browse your docsets, you can do: =(setq ddoc-browser-func 'eww)=.

  When =ddoc-enable-debugging= is non-nil stderr from sqlite queries is
  captured and displayed in a buffer. The default value is =t=. Setting this
  to =nil= may speed up queries on some machines (capturing stderr requires
  the creation and deletion of a temporary file for each query).

* Variables
** Common

   - =ddoc-common-docsets= :: is a list that should contain the
     docsets to be active always. In all buffers.

** Local

   Different subsets of docsets can be activated depending on the
   buffer. For the moment (it may change in the future) we decided it's a
   plain local variable you should setup for every different file type.

   This way you can also do fancier things like project-wise
   docsets sets.

   #+BEGIN_SRC emacs-lisp

   (defun go-set-docset ()
     (interactive)
     (setq-local ddoc-docsets '("Go")))

   ;; add hook
   (add-hook 'go-mode-hook 'go-set-docset)

   #+END_SRC

* FAQ

  - Does it works in MacOS/Windows?
    Duno...

  - Does it works in Linux/BSDs?
    Yeap!

  - When selecting an item in ddoc, no browser
    lookup occurs with =Firefox= and =Emacs= >= 24.4: \\

    Try: \\

    #+BEGIN_SRC emacs-lisp
    ;; customize function to display the current
    ;; buffer in a ww browser
    (customize-set-variable 'browse-url-browser-function 'browse-url-generic)

    ;; customize the name of the browser program used
    ;; by `browse-url-generic'
    (customize-set-variable 'browse-url-generic-program "/path/to/firefox")

    ;; customize default function to browse Dash’s docsets
    (customize-set-variable 'ddoc-browser-func 'browse-url-generic)
    #+END_SRC

* References

  1. https://kapeli.com/dash
  2. https://github.com/dash-docs-el/dash-docs
  3. https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html

* LICENSE
  MIT
* EOF

  #+BEGIN_SRC
  Computer science is no more about computers
  than astronomy is about telescopes.
  #+END_SRC
  | Edsger Dijkstra |
